import {
  MAX_NUMBER,
  MAX_SIZE,
  TYPE_FILE_IMAGE,
} from "@/constants/dropzoneConstants";
import {
  INPUT_TEXT,
  INPUT_DATE,
  MAX_LENGTH,
  CITY_LIST,
  INPUT_AREA,
  MAX_LENGTH_AREA,
  INPUT_SALARY,
  MAX_LENGTH_NUMBER,
  INPUT_DROPDOWN_SEARCH,
  POSITION_LIST,
  MAX_LENGTH_PASSWORD,
} from "@/constants/registerFormConstants";
const accountForm = [
  {
    label: "Username",
    view_type: INPUT_TEXT,
    key: "username",
    required: true,
    value: "",
    error: "",
    maxLength: MAX_LENGTH,
  },
  {
    label: "Password",
    view_type: INPUT_TEXT,
    key: "password",
    type: "password",
    required: true,
    value: "",
    error: "",
    maxLength: MAX_LENGTH_PASSWORD,
  },
  {
    label: "Repeat Password",
    view_type: INPUT_TEXT,
    key: "re-password",
    type: "password",
    required: true,
    value: "",
    error: "",
    maxLength: MAX_LENGTH_PASSWORD,
  },
];
const profileForm = [
  {
    label: "Fullname",
    view_type: INPUT_TEXT,
    required: true,
    value: "",
    key: "fullname",
    error: "",
    maxLength: MAX_LENGTH,
  },
  {
    label: "Birthday",
    view_type: INPUT_DATE,
    required: true,
    value: "",
    key: "dob",
    error: "",
  },
  {
    label: "City",
    view_type: "input-dropdown",
    required: false,
    value: "",
    key: "city",
    cityList: CITY_LIST,
  },
  {
    label: "Position",
    view_type: INPUT_DROPDOWN_SEARCH,
    required: false,
    key: "position",
    value: [],
    optionList: POSITION_LIST,
  },
  {
    label: "Describe Yourself",
    view_type: INPUT_AREA,
    required: false,
    value: "",
    key: "about_me",
    error: "",
    maxLength: MAX_LENGTH_AREA,
  },
  {
    label: "Avatar (only one)",
    view_type: "img-dropzone",
    required: false,
    value: [],
    key: "avatar",
    maxSize: MAX_SIZE,
    maxNumber: MAX_NUMBER,
    typeFile: TYPE_FILE_IMAGE,
  },
];
const finishedForm = [
  {
    label: "Reason",
    view_type: INPUT_AREA,
    required: true,
    value: "",
    key: "reason",
    error: "",
    maxLength: MAX_LENGTH_AREA,
  },
  {
    label: "Wish salary",
    view_type: INPUT_SALARY,
    required: true,
    value: "",
    key: "salary",
    error: "",
    maxLength: MAX_LENGTH_NUMBER,
  },
];
const registerForm = [
  {
    id: 1,
    num: 1,
    data: accountForm,
    name: "Account",
    isDone: false,
  },
  {
    id: 2,
    num: 2,
    name: "Profile",
    data: profileForm,
    isDone: false,
  },
  {
    id: 3,
    num: 3,
    data: finishedForm,
    name: "Finished",
    isDone: false,
  },
];
export { registerForm };
